2013-12-04 18:55:30,097 - [INFO] - from play in pool-25-thread-3 
Listening for HTTP on /0:0:0:0:0:0:0:0%0:9000

2013-12-04 18:55:35,269 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:h2:mem:play] bound to JNDI as DefaultDS

2013-12-04 18:55:35,303 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:mem:play

2013-12-04 18:55:35,818 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2013-12-04 18:56:29,313 - [INFO] - from play in main 
datasource [jdbc:h2:mem:play] bound to JNDI as DefaultDS

2013-12-04 18:56:29,636 - [INFO] - from play in main 
database [default] connected at jdbc:h2:mem:play

2013-12-04 18:56:31,112 - [INFO] - from play in main 
Application started (Prod)

2013-12-04 18:56:31,262 - [INFO] - from play in main 
Listening for HTTP on /0:0:0:0:0:0:0:0%0:9000

2013-12-04 19:40:40,824 - [INFO] - from play in main 
datasource [jdbc:h2:mem:play] bound to JNDI as DefaultDS

2013-12-04 19:40:41,116 - [INFO] - from play in main 
database [default] connected at jdbc:h2:mem:play

2013-12-04 19:40:42,790 - [INFO] - from play in main 
Application started (Prod)

2013-12-04 19:40:44,772 - [ERROR] - from play in play-internal-execution-context-1 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:Table "TASK" not found; SQL statement:
select t0.id c0, t0.label c1 from task t0 [42102-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.label c1 from task t0 



2013-12-04 19:40:44,792 - [ERROR] - from application in play-internal-execution-context-1 


! @6gf88e79n - Internal server error, for (GET) [/tasks] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:Table "TASK" not found; SQL statement:
select t0.id c0, t0.label c1 from task t0 [42102-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.label c1 from task t0 

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.0]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.0]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:257) [play_2.10.jar:2.2.0]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:411) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:408) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.0]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:37) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:133) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:58) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:254) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Table "TASK" not found; SQL statement:
select t0.id c0, t0.label c1 from task t0 [42102-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.label c1 from task t0 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:885) ~[avaje-ebeanorm.jar:na]
	at play.db.ebean.Model$Finder.all(Model.java:254) ~[play-java-ebean_2.10.jar:2.2.0]
	at models.Task.all(Task.java:24) ~[classes/:na]
	at controllers.Application.tasks(Application.java:36) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:89) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:89) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.0]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.0]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.0]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.0]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.0]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.0]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.0]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:278) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:274) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.0]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Table "TASK" not found; SQL statement:
select t0.id c0, t0.label c1 from task t0 [42102-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.readTableOrView(Parser.java:4824) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.readTableFilter(Parser.java:1099) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1705) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1813) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parseSelectSub(Parser.java:1699) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1542) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parseSelect(Parser.java:1530) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parsePrepared(Parser.java:405) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parse(Parser.java:279) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parse(Parser.java:251) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.prepareCommand(Parser.java:218) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareLocal(Session.java:425) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareCommand(Session.java:374) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267) ~[h2.jar:1.3.172]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:979) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:360) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:162) ~[avaje-ebeanorm.jar:na]
	... 26 common frames omitted

2013-12-04 19:44:31,099 - [INFO] - from play in main 
datasource [jdbc:h2:mem:play] bound to JNDI as DefaultDS

2013-12-04 19:44:31,317 - [INFO] - from play in main 
database [default] connected at jdbc:h2:mem:play

2013-12-04 19:44:32,656 - [WARN] - from play in main 
Your production database [default] needs evolutions! 

# --- Rev:1,Ups - 59cbd8e
create table game (
id                        bigint not null,
turn                      integer,
board                     clob,
win_streak                clob,
constraint ck_game_turn check (turn in (0,1)),
constraint pk_game primary key (id))
;

create table task (
id                        bigint not null,
label                     varchar(255),
constraint pk_task primary key (id))
;

create sequence game_seq;

create sequence task_seq;


2013-12-04 19:44:32,657 - [WARN] - from play in main 
Run with -DapplyEvolutions.default=true if you want to run them automatically (be careful)

2013-12-04 19:44:36,374 - [ERROR] - from play in play-internal-execution-context-1 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:Table "TASK" not found; SQL statement:
select t0.id c0, t0.label c1 from task t0 [42102-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.label c1 from task t0 



2013-12-04 19:44:36,376 - [ERROR] - from application in play-internal-execution-context-1 


! @6gf891bpa - Internal server error, for (GET) [/tasks] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:Table "TASK" not found; SQL statement:
select t0.id c0, t0.label c1 from task t0 [42102-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.label c1 from task t0 

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.0]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.0]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:257) [play_2.10.jar:2.2.0]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:411) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:408) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.0]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:37) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:133) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:58) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:254) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Table "TASK" not found; SQL statement:
select t0.id c0, t0.label c1 from task t0 [42102-172] 
Bind values:[null] 
Query was:
select t0.id c0, t0.label c1 from task t0 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:885) ~[avaje-ebeanorm.jar:na]
	at play.db.ebean.Model$Finder.all(Model.java:254) ~[play-java-ebean_2.10.jar:2.2.0]
	at models.Task.all(Task.java:24) ~[classes/:na]
	at controllers.Application.tasks(Application.java:36) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:89) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:89) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.0]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.0]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.0]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.0]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.0]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.0]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.0]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:278) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:274) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.0]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Table "TASK" not found; SQL statement:
select t0.id c0, t0.label c1 from task t0 [42102-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.readTableOrView(Parser.java:4824) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.readTableFilter(Parser.java:1099) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1705) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1813) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parseSelectSub(Parser.java:1699) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1542) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parseSelect(Parser.java:1530) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parsePrepared(Parser.java:405) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parse(Parser.java:279) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.parse(Parser.java:251) ~[h2.jar:1.3.172]
	at org.h2.command.Parser.prepareCommand(Parser.java:218) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareLocal(Session.java:425) ~[h2.jar:1.3.172]
	at org.h2.engine.Session.prepareCommand(Session.java:374) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70) ~[h2.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267) ~[h2.jar:1.3.172]
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:979) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:360) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:162) ~[avaje-ebeanorm.jar:na]
	... 26 common frames omitted

2013-12-04 19:48:21,682 - [INFO] - from play in main 
datasource [jdbc:h2:mem:play] bound to JNDI as DefaultDS

2013-12-04 19:48:21,959 - [INFO] - from play in main 
database [default] connected at jdbc:h2:mem:play

2013-12-04 19:48:23,395 - [INFO] - from play in main 
Application started (Prod)

2013-12-04 19:49:44,471 - [INFO] - from play in main 
datasource [jdbc:h2:mem:play] bound to JNDI as DefaultDS

2013-12-04 19:49:44,659 - [INFO] - from play in main 
database [default] connected at jdbc:h2:mem:play

2013-12-04 19:49:45,794 - [INFO] - from play in main 
Application started (Prod)

2013-12-04 19:49:45,904 - [INFO] - from play in main 
Listening for HTTP on /0:0:0:0:0:0:0:0%0:9000

